---
name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/aristanetworks/avd/universal:python3.11-avd-v4.8.0
      options: --user 1001
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.11/site-packages"

    steps:
      # https://github.com/actions/runner/issues/863
      - shell: bash
        run: 'echo HOME=/home/avd | sudo tee -a $GITHUB_ENV'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          make build
