---
name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/aristanetworks/avd/universal:python3.11-avd-v4.7.1
      # options: --user 0
      options: --user 1001
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.11/site-packages"

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: check UID
        run: |
          id -u
          id -g

      - name: start cLab
        run: |
          export CLAB_VERSION="0.54.2"
          bash -c "$(curl -sL https://get.containerlab.dev)" -- -v ${CLAB_VERSION}
          export CEOS_LAB_VERSION="4.32.1F"
          pip install "eos-downloader>=0.10.1"
          ardl --token "${{ secrets.ARTOKEN }}" get eos --image-type cEOS --version ${CEOS_LAB_VERSION}  --import-docker
          make start

      - name: Build
        run: |
          pip install passlib
          make build
