---
name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/aristanetworks/avd/universal:python3.11-avd-v4.8.0
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          make build
