---
name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/aristanetworks/avd/universal:python3.11-avd-v4.8.0
      options: --user 1
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.11/site-packages"

    steps:
      # https://github.com/actions/runner/issues/863
      - name: setup homedir
        id: setup-homedir
        uses: actions/github-script@v6
        env:
          CONTAINER_ID: ${{ job.container.id }}
        with:
          result-encoding: string
          script: |
            const z = process.env.CONTAINER_ID;
            if (z) {
              const newhome = `/home/avd`;
              await io.mkdirP(newhome);
              core.exportVariable("HOME", newhome);
              return newhome;
            }
            return process.env.HOME;

      - name: Checkout code
        uses: actions/checkout@v3

      - name: check UID
        run: |
          id -u
          id -g

      - name: Build
        run: |
          make build
