---
name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/aristanetworks/avd/universal:python3.11-avd-v4.7.1
      # options: --user 0
      options: --user 1001
      env:
        PYTHONPATH: "/home/avd/.local/lib/python3.11/site-packages"

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: check UID
        run: |
          id -u
          id -g

      - name: Build
        run: |
          pip install passlib
          make build
