# this workflow can be triggered manually to initiate any build if it fails
name: fix container build

on:
  workflow_dispatch:
    inputs:
      container_name:
        type: choice
        required: true
        description: "select image name to build"
        options: [universal]
        default: "universal"
      container_tags:
        type: string
        required: false
        description: "container image tags"
        default: "fix"  # this is a special tag that can be used for testing
      python_version:
        type: choice
        required: true
        description: "select Python version"
        options: ["3.10", "3.11", "3.12", "3.13"]
        default: "3.11"
      github_tag:
        type: string
        required: true
        description: "Github tag/branch that will be used to build the image"
      github_repo:
        type: string
        required: true
        description: "Github repo name"

jobs:
  fix_container_build:
    uses: ./.github/workflows/container_build_template.yml
    with:
      container_name: ${{ inputs.container_name }}
      container_tags: ${{ inputs.container_tags }}
      python_version: ${{ inputs.python_version }}
      github_tag: ${{ inputs.github_tag }}
      github_repo: ${{ inputs.github_repo }}
