---
name: test if condition

on:
  push:
  release:
    types: [published]

# env:
#   run_workflow: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build:
    if: ( github.repository == 'ankudinov/test-gh-ci-with-devcontainer' && ( github.ref == 'refs/heads/main' || github.event.action == 'published' ) ) || vars.DEBUG_CONTAINER_ACTIONS == 'false'
    runs-on: ubuntu-latest
    steps:

      - name: check UID
        run: |
          id -u
          id -g
          echo "Testing if condition!"
          echo "${{ vars.DEBUG_CONTAINER_ACTIONS }}"
