---
name: test if condition

on:
  push:
    branches:
      - main

jobs:
  build:
    # if: ( github.repository == 'aristanetworks/avd' && github.ref == 'refs/heads/devel' ) || ${{ vars.DEBUG_CONTAINER_ACTIONS }} == "true"
    # if: ${{ vars.DEBUG_CONTAINER_ACTIONS }} == "false"
    if: ( github.repository == 'aristanetworks/avd' && github.ref == 'refs/heads/devel' ) || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: check UID
        run: |
          id -u
          id -g
          echo "Testing if condition!"
