---
name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ( github.repository == 'aristanetworks/avd' && github.ref == 'refs/heads/devel' ) || ${{ vars.DEBUG_CONTAINER_ACTIONS }} == "true"
    runs-on: ubuntu-latest
    steps:

      - name: check UID
        run: |
          id -u
          id -g
